version: '3.1'

services:
  pgsql:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: minijo123
      POSTGRES_PASSWORD: miata123
      POSTGRES_DB: minijo
    volumes:
      - ~/docker-data/postgresql/data:/var/lib/postgresql/data