version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: minijo123
      POSTGRES_PASSWORD: miata123
      POSTGRES_DB: minijo
    volumes:
      - ~/docker-data/postgresql/data:/var/lib/postgresql/data
  app:
    build: .
    command: ["/bin/wait-for-it.sh", "db:5432", "--", "/bin/main"]
    ports:
      - 5000:5000
    environment: 
      USER_DB: minijo123
      PASS_DB: miata123
      NAME_DB: minijo
      HOST_DB: db
      PORT_DB: 5432
    depends_on:
      - db