version: '3.1'

services:
  db:
    image: postgres
    container_name: minijo-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: minijo123
      POSTGRES_PASSWORD: miata123
      POSTGRES_DB: minijo
    volumes:
      - ~/docker-data/postgresql/data:/var/lib/postgresql/data
  backend:
    build: ./minijo-backend/
    container_name: minijo-backend
    command: ["/bin/wait-for-it.sh", "db:5432", "--", "/bin/main"]
    ports:
      - 5000:5000
    environment: 
      USER_DB: minijo123
      PASS_DB: miata123
      NAME_DB: minijo
      HOST_DB: minijo-db
      PORT_DB: 5432
    depends_on:
      - db
  minijo-frontend:
    build: ./minijo-frontend/
    container_name: minijo-frontend
    ports:
      - 3000:80

